server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demodb?serverTimezone=GMT%2B8
    username: root
    password: root
#  jpa:
#    hibernate:
#      ddl-auto: create

#security:
#  user:
#    name:root
#    password:root





